*&---------------------------------------------------------------------*
*&  Include           ZBP_MIGS4_TOP
*&---------------------------------------------------------------------*
INITIALIZATION.

  TYPE-POOLS: icon, abap, slis, sx.
  TABLES: kna1, lfa1.
  SELECTION-SCREEN BEGIN OF SCREEN 400 AS SUBSCREEN.
  SELECT-OPTIONS: s_stcd1 FOR kna1-stcd1, "NIF
                  s_kunnr FOR kna1-kunnr, "Cliente
                  s_lifnr FOR lfa1-lifnr. "Proveedor
  SELECTION-SCREEN END OF SCREEN 400 .
*&---------------------------------------------------------------------*
*&                            CONSTANTES                               *
*&---------------------------------------------------------------------*
  CONSTANTS: BEGIN OF c_pes1,
               tab1 LIKE sy-ucomm VALUE 'PES1_FC1',
               tab2 LIKE sy-ucomm VALUE 'PES1_FC2',
               tab3 LIKE sy-ucomm VALUE 'PES1_FC3',
               tab4 LIKE sy-ucomm VALUE 'PES1_FC4',
             END OF c_pes1,

             c_int(3)           TYPE c VALUE 'INT',
             c_ic1(4)           TYPE c VALUE '&IC1',
             c_kunnr(5)         TYPE c VALUE 'KUNNR',
             c_lifnr(5)         TYPE c VALUE 'LIFNR',
             c_ktokd(5)         TYPE c VALUE 'KTOKD',
             c_ktokk(5)         TYPE c VALUE 'KTOKK',
             c_loevm(5)         TYPE c VALUE 'LOEVM',
             c_name1(5)         TYPE c VALUE 'NAME1',
             c_name2(5)         TYPE c VALUE 'NAME2',
             c_stcd5(5)         TYPE c VALUE 'STCD5',
             c_numero(6)        TYPE c VALUE 'NUMERO',
             c_prueba(6)        TYPE c VALUE 'PRUEBA',
             c_semaforo(8)      TYPE c VALUE 'SEMAFORO',
             c_comentario(10)   TYPE c VALUE 'COMENTARIO',
             c_user_command(30) TYPE c VALUE 'F_USER_COMMAND',
             c_addr(22)         TYPE c VALUE 'ADDR_POSTAL_CODE_CHECK',
             c_progress(25)     TYPE c VALUE 'SAPGUI_PROGRESS_INDICATOR',
             c_bapi_bupa(25)    TYPE c VALUE 'BAPI_BUPA_BANKDETAILS_GET',
             c_alv_grid(26)     TYPE c VALUE 'REUSE_ALV_GRID_DISPLAY_LVC',
             c_address(29)      TYPE c VALUE 'SX_INTERNET_ADDRESS_TO_NORMAL',
             c_globals(29)      TYPE c VALUE 'GET_GLOBALS_FROM_SLVC_FULLSCR',
*           "INI ZPRY_PRS4 03.04.2024 54217049T
             c_stcd1(16)        TYPE c VALUE 'TAX_NUMBER_CHECK',
             c_target(6)        TYPE c VALUE 'TARGET',
             c_cp               TYPE c VALUE ''.
*           "FIN ZPRY_PRS4

  CONTROLS:  pes1 TYPE TABSTRIP.


*&---------------------------------------------------------------------*
*&                            TIPOS                                    *
*&---------------------------------------------------------------------*
  TYPES: BEGIN OF ty_alv_principal,
           numero     TYPE i,
           prueba     TYPE cts_filename,
           comentario TYPE cts_filename,
           semaforo   TYPE icon_d,
         END   OF ty_alv_principal,

         BEGIN OF ty_kna1,
           kunnr TYPE kna1-kunnr,
           land1 TYPE kna1-land1,
           name1 TYPE kna1-name1,
           name2 TYPE kna1-name2,
           pstlz TYPE kna1-pstlz,
           regio TYPE kna1-regio,
           adrnr TYPE kna1-adrnr,
           ktokd TYPE kna1-ktokd,
           lifnr TYPE kna1-lifnr,
           loevm TYPE kna1-loevm,
           stcd1 TYPE kna1-stcd1,
           stcd2 TYPE kna1-stcd2,
           stceg TYPE kna1-stceg,
           stcd3 TYPE kna1-stcd3,
           stcd4 TYPE kna1-stcd4,
           stcd5 TYPE kna1-stcd5,
           anred TYPE lfa1-anred, ""INI ZPRY_PRS4 03.04.2024 54217049T
         END   OF ty_kna1,

         BEGIN OF ty_kna1_log,
           kunnr      TYPE kna1-kunnr,
           ktokd      TYPE kna1-ktokd,
           loevm      TYPE kna1-loevm,
           name1      TYPE kna1-name1,
           name2      TYPE kna1-name2,
           stcd5      TYPE kna1-stcd5,
           comentario TYPE cts_filename,
         END   OF ty_kna1_log,

         BEGIN OF ty_lfa1,
           lifnr TYPE lfa1-lifnr,
           land1 TYPE lfa1-land1,
           name1 TYPE lfa1-name1,
           name2 TYPE lfa1-name2,
           pstlz TYPE lfa1-pstlz,
           regio TYPE lfa1-regio,
           adrnr TYPE lfa1-adrnr,
           ktokk TYPE lfa1-ktokk,
           kunnr TYPE lfa1-kunnr,
           loevm TYPE lfa1-loevm,
           stcd1 TYPE lfa1-stcd1,
           stcd2 TYPE lfa1-stcd2,
           stceg TYPE lfa1-stceg,
           stcd3 TYPE lfa1-stcd3,
           stcd4 TYPE lfa1-stcd4,
           stcd5 TYPE lfa1-stcd5,
           anred TYPE lfa1-anred, ""INI ZPRY_PRS4 03.04.2024 54217049T
         END   OF ty_lfa1,

         BEGIN OF ty_lfa1_log,
           lifnr      TYPE lfa1-lifnr,
           ktokk      TYPE lfa1-ktokk,
           loevm      TYPE lfa1-loevm,
           name1      TYPE lfa1-name1,
           name2      TYPE lfa1-name2,
           stcd5      TYPE lfa1-stcd5,
           comentario TYPE cts_filename,
         END   OF ty_lfa1_log,

         BEGIN OF ty_cruce,
           stcd5  TYPE lfa1-stcd5,
           kkunnr TYPE kna1-kunnr,
           klifnr TYPE kna1-lifnr,
           ktokd  TYPE kna1-ktokd,
           kloevm TYPE kna1-loevm,
           kname1 TYPE kna1-name1,
           kname2 TYPE kna1-name2,
           llifnr TYPE lfa1-lifnr,
           lkunnr TYPE lfa1-kunnr,
           ktokk  TYPE lfa1-ktokk,
           lloevm TYPE lfa1-loevm,
           lname1 TYPE lfa1-name1,
           lname2 TYPE lfa1-name2,
         END OF ty_cruce,

         BEGIN OF ty_cliente_proveedor,
           kunnr      TYPE kna1-kunnr,
           lifnr      TYPE kna1-lifnr,
           stcd1      TYPE kna1-stcd1,
           addrnumber TYPE adrc-addrnumber,
           date_from  TYPE adrc-date_from,
           nation     TYPE adrc-nation,
           date_to    TYPE adrc-date_to,
           title      TYPE adrc-title,
           name1      TYPE adrc-name1,
           name2      TYPE adrc-name2,
           name3      TYPE adrc-name3,
           name4      TYPE adrc-name4,
           name_text  TYPE adrc-name_text,
           name_co    TYPE adrc-name_co,
           city1      TYPE adrc-city1,
           city2      TYPE adrc-city2,
           city_code  TYPE adrc-city_code,
           cityp_code TYPE adrc-cityp_code,
           home_city  TYPE adrc-home_city,
           cityh_code TYPE adrc-cityh_code,
           chckstatus TYPE adrc-chckstatus,
           regiogroup TYPE adrc-regiogroup,
           post_code1 TYPE adrc-post_code1,
           post_code2 TYPE adrc-post_code2,
           post_code3 TYPE adrc-post_code3,
           pcode1_ext TYPE adrc-pcode1_ext,
           pcode2_ext TYPE adrc-pcode2_ext,
           pcode3_ext TYPE adrc-pcode3_ext,
           po_box     TYPE adrc-po_box,
           dont_use_p TYPE adrc-dont_use_p,
           po_box_num TYPE adrc-po_box_num,
           po_box_loc TYPE adrc-po_box_loc,
           city_code2 TYPE adrc-city_code2,
           po_box_reg TYPE adrc-po_box_reg,
           po_box_cty TYPE adrc-po_box_cty,
           postalarea TYPE adrc-postalarea,
           transpzone TYPE adrc-transpzone,
           street     TYPE adrc-street,
           dont_use_s TYPE adrc-dont_use_s,
           streetcode TYPE adrc-streetcode,
           streetabbr TYPE adrc-streetabbr,
           house_num1 TYPE adrc-house_num1,
           house_num2 TYPE adrc-house_num2,
           house_num3 TYPE adrc-house_num3,
           str_suppl1 TYPE adrc-str_suppl1,
           str_suppl2 TYPE adrc-str_suppl2,
           str_suppl3 TYPE adrc-str_suppl3,
           location   TYPE adrc-location,
           building   TYPE adrc-building,
           floor      TYPE adrc-floor,
           roomnumber TYPE adrc-roomnumber,
           country    TYPE adrc-country,
           langu      TYPE adrc-langu,
           region     TYPE adrc-region,
           addr_group TYPE adrc-addr_group,
           flaggroups TYPE adrc-flaggroups,
           pers_addr  TYPE adrc-pers_addr,
           sort1      TYPE adrc-sort1,
           sort2      TYPE adrc-sort2,
           sort_phn   TYPE adrc-sort_phn,
           deflt_comm TYPE adrc-deflt_comm,
           tel_number TYPE adrc-tel_number,
           tel_extens TYPE adrc-tel_extens,
           fax_number TYPE adrc-fax_number,
           fax_extens TYPE adrc-fax_extens,
           flagcomm2  TYPE adrc-flagcomm2,
           flagcomm3  TYPE adrc-flagcomm3,
           flagcomm4  TYPE adrc-flagcomm4,
           flagcomm5  TYPE adrc-flagcomm5,
           flagcomm6  TYPE adrc-flagcomm6,
           flagcomm7  TYPE adrc-flagcomm7,
           flagcomm8  TYPE adrc-flagcomm8,
           flagcomm9  TYPE adrc-flagcomm9,
           flagcomm10 TYPE adrc-flagcomm10,
           flagcomm11 TYPE adrc-flagcomm11,
           flagcomm12 TYPE adrc-flagcomm12,
           flagcomm13 TYPE adrc-flagcomm13,
           addrorigin TYPE adrc-addrorigin,
           mc_name1   TYPE adrc-mc_name1,
           mc_city1   TYPE adrc-mc_city1,
           mc_street  TYPE adrc-mc_street,
           extension1 TYPE adrc-extension1,
           extension2 TYPE adrc-extension2,
           time_zone  TYPE adrc-time_zone,
           taxjurcode TYPE adrc-taxjurcode,
           address_id TYPE adrc-address_id,
           langu_crea TYPE adrc-langu_crea,
         END   OF ty_cliente_proveedor,

         BEGIN OF ty_cliente_proveedor_log,
           kunnr      TYPE kna1-kunnr,
           lifnr      TYPE kna1-lifnr,
           comentario TYPE cts_filename,
         END   OF ty_cliente_proveedor_log,

         BEGIN OF ty_cliente_db,
           kunnr         TYPE kna1-kunnr,
           lifnr         TYPE kna1-lifnr,
           banks         TYPE knbk-banks,
           bankl         TYPE knbk-bankl,
           bankn         TYPE knbk-bankn,
           bkont         TYPE knbk-bkont,
           bvtyp         TYPE knbk-bvtyp,
           xezer         TYPE knbk-xezer,
           bkref         TYPE knbk-bkref,
           koinh         TYPE knbk-koinh,
           ebpp_accname  TYPE knbk-ebpp_accname,
           ebpp_bvstatus TYPE knbk-ebpp_bvstatus,
           kovon         TYPE knbk-kovon,
           kobis         TYPE knbk-kobis,
         END   OF ty_cliente_db,

         BEGIN OF ty_proveedor_db,
           lifnr         TYPE lfa1-lifnr,
           kunnr         TYPE lfa1-kunnr,
           banks         TYPE lfbk-banks,
           bankl         TYPE lfbk-bankl,
           bankn         TYPE lfbk-bankn,
           bkont         TYPE lfbk-bkont,
           bvtyp         TYPE lfbk-bvtyp,
           xezer         TYPE lfbk-xezer,
           bkref         TYPE lfbk-bkref,
           koinh         TYPE lfbk-koinh,
           ebpp_accname  TYPE lfbk-ebpp_accname,
           ebpp_bvstatus TYPE lfbk-ebpp_bvstatus,
           kovon         TYPE lfbk-kovon,
           kobis         TYPE lfbk-kobis,
         END   OF ty_proveedor_db,

         BEGIN OF ty_cliente_proveedor_db_log,
           kunnr      TYPE kna1-kunnr,
           lifnr      TYPE kna1-lifnr,
           comentario TYPE cts_filename,
         END   OF ty_cliente_proveedor_db_log,

         BEGIN OF ty_knbk,
           kunnr TYPE knbk-kunnr,
           banks TYPE knbk-banks,
           bankl TYPE knbk-bankl,
         END   OF ty_knbk,

         BEGIN OF ty_lfbk,
           lifnr TYPE lfbk-lifnr,
           banks TYPE lfbk-banks,
           bankl TYPE lfbk-bankl,
         END   OF ty_lfbk,

         BEGIN OF ty_bnka_log,
           kunnr      TYPE kna1-kunnr,
           banks      TYPE bnka-banks,
           bankl      TYPE bnka-bankl,
           comentario TYPE cts_filename,
         END   OF ty_bnka_log,

         BEGIN OF ty_nif_log,
           taxtype    TYPE tfktaxnumtype-taxtype,
           comentario TYPE cts_filename,
         END   OF ty_nif_log,

         BEGIN OF ty_postal_log,
           kunnr      TYPE kna1-kunnr,
           land1      TYPE kna1-land1,
           pstlz      TYPE kna1-pstlz,
           regio      TYPE kna1-regio,
           comentario TYPE cts_filename,
         END   OF ty_postal_log,

         BEGIN OF ty_correoe_log,
           kunnr      TYPE kna1-kunnr,
           smtp_addr  TYPE adr6-smtp_addr,
           comentario TYPE cts_filename,
         END   OF ty_correoe_log,

         BEGIN OF ty_cuadre_log,
           kunnr      TYPE kna1-kunnr,
           ktokd      TYPE kna1-ktokd,
           comentario TYPE cts_filename,
         END OF ty_cuadre_log,

         BEGIN OF ty_bp_creado_log,
           partner  TYPE but000-partner,
           bu_group TYPE but000-bu_group,
         END OF ty_bp_creado_log,

**       "INI ZPRY_PRS4 03.04.2024 54217049T
         BEGIN OF ty_stcd1_log,
           target     TYPE c LENGTH 10,
           stcd1      TYPE stcd1,
           comentario TYPE cts_filename,
           land1      TYPE land1,
         END   OF ty_stcd1_log,

         BEGIN OF ty_pstlz_log,
           target     TYPE c LENGTH 10,
           comentario TYPE cts_filename,
           land1      TYPE land1,
         END   OF ty_pstlz_log,

         BEGIN OF ty_anred_log,
           target     TYPE c LENGTH 10,
           comentario TYPE cts_filename,
         END   OF ty_anred_log,

         BEGIN OF ty_t005,
           land1 TYPE land1,
           xplzs TYPE xplzs_005,
         END   OF ty_t005,
**       "FIN ZPRY_PRS4

         BEGIN OF ty_chequeo_p_log,
           nif            TYPE  char20,
           partner        TYPE  bu_partner,
           bankdetailid   TYPE  bu_bkvid,
           banks          TYPE  banks,
           bankl          TYPE  bankl,
           bankn          TYPE  bankn,
           bkont          TYPE  bkont,
           iban           TYPE  iban,
           kunnr          TYPE  kunnr,
           bankdetailid_k TYPE  bu_bkvid,
           banks_k        TYPE  banks,
           bankl_k        TYPE  bankl,
           bankn_k        TYPE  bankn,
           bkont_k        TYPE  bkont,
           iban_k         TYPE  iban,
           asociado       TYPE  char2,
           lifnr          TYPE  lifnr,
           bankdetailid_l TYPE  bu_bkvid,
           banks_l        TYPE  banks,
           bankl_l        TYPE  bankl,
           bankn_l        TYPE  bankn,
           bkont_l        TYPE  bkont,
           iban_l         TYPE  iban,
         END OF ty_chequeo_p_log

         .


  DATA: BEGIN OF g_pes1,
          subscreen   LIKE sy-dynnr,
          prog        LIKE sy-repid VALUE 'ZBP_MIGS4',
          pressed_tab LIKE sy-ucomm VALUE c_pes1-tab1,
        END OF g_pes1.

*&---------------------------------------------------------------------*
*&                            TABLAS INTERNAS                          *
*&---------------------------------------------------------------------*
  DATA:
    i_alv_principal     TYPE TABLE OF ty_alv_principal,
    i_kna1              TYPE TABLE OF ty_kna1,
    i_lfa1              TYPE TABLE OF ty_lfa1,
    i_kna1_cliente      TYPE TABLE OF ty_cliente_proveedor,
    i_kna1_cliente_db   TYPE TABLE OF ty_cliente_db,
    i_lfa1_proveedor    TYPE TABLE OF ty_cliente_proveedor,
    i_lfa1_proveedor_db TYPE TABLE OF ty_proveedor_db,
    i_knbk              TYPE TABLE OF ty_knbk,
    i_lfbk              TYPE TABLE OF ty_lfbk,
    i_kna1_log          TYPE TABLE OF ty_kna1_log,
    i_lfa1_log          TYPE TABLE OF ty_lfa1_log,
    i_cruce_log         TYPE TABLE OF ty_cruce,
    i_cp_log            TYPE TABLE OF ty_cliente_proveedor_log,
    i_cp_db_log         TYPE TABLE OF ty_cliente_proveedor_db_log,
    i_bnka_log          TYPE TABLE OF ty_bnka_log,
    i_nif_log           TYPE TABLE OF ty_nif_log,
    i_postal_log        TYPE TABLE OF ty_postal_log,
    i_correoe_log       TYPE TABLE OF ty_correoe_log,
**  "INI ZPRY_PRS4 03.04.2024 54217049T
    i_stcd1_log         TYPE TABLE OF ty_stcd1_log,
    i_pstlz_log         TYPE TABLE OF ty_pstlz_log,
    i_anred_log         TYPE TABLE OF ty_anred_log,
**  "FIN ZPRY_PRS4
    i_cuadre_log        TYPE TABLE OF ty_cuadre_log,
    i_bp_creado_log     TYPE TABLE OF ty_bp_creado_log,
    i_chequeo_p_log     TYPE TABLE OF ty_chequeo_p_log,
    i_catalogo          TYPE TABLE OF lvc_s_fcat.

*&---------------------------------------------------------------------*
*&                            VARIABLES                                *
*&---------------------------------------------------------------------*
  DATA: p_1     TYPE checkbox VALUE abap_true,
        p_2     TYPE checkbox VALUE abap_true,
        p_3     TYPE checkbox VALUE abap_true,
        p_4     TYPE checkbox VALUE abap_true,
        p_5     TYPE checkbox VALUE abap_true,
        p_6     TYPE checkbox VALUE abap_true,
        p_7     TYPE checkbox VALUE abap_true,
        p_8     TYPE checkbox VALUE abap_true,
        p_9     TYPE checkbox VALUE abap_true,
        p_10    TYPE checkbox VALUE abap_false,
        p_11    TYPE checkbox VALUE abap_true,
        p_12    TYPE checkbox VALUE abap_true,
        p_13    TYPE checkbox VALUE abap_true,
        p_14    TYPE checkbox VALUE abap_true,
*      "INI ZPRY_PRS4 03.04.2024 54217049T
        p_10b   TYPE checkbox VALUE abap_true,
        p_11b   TYPE checkbox VALUE abap_true,
        p_12b   TYPE checkbox VALUE abap_true,
*      "FIN ZPRY_PRS4
        ok_code TYPE sy-ucomm.
  DATA: gt_users     TYPE TABLE OF rgsbv,
        gv_superuser TYPE abap_bool.

  INCLUDE inclkons.

AT SELECTION-SCREEN OUTPUT.
  PERFORM f_ocultar_campos.
